/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package catalogue_java_db;


import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JList;
/**
 *
 * @author Bamba Mohamed
 */
public class FenetreMain extends javax.swing.JFrame {
    private ConfirmCommande cc;
    private List<TitreCode> listeCode;
    private ModelListeCode mlc;
    Connection connection = null;
    PreparedStatement requete = null;
    ResultSet resultat = null;
    /**
     * Creates new form FenetreMain
     * @param listeCode
     */
    public FenetreMain(List<TitreCode> listeCode) {
        
        this.listeCode = listeCode;
        mlc = new ModelListeCode(listeCode);
        
        initComponents();
        cc = new ConfirmCommande(this, true);
        // mise en place de l'icône de l'application
        Toolkit tk = Toolkit.getDefaultToolkit();
        Image im = tk.getImage(getClass().getResource("/image/euro.png"));
        ImageIcon icon = new ImageIcon(im);
        setIconImage(icon.getImage());
        
        try {
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver"); // chargement du pilote (driver) permettant d'accéder au SGBDR
            connection = DriverManager.getConnection("jdbc:derby:bd_listecode;create=true"); // chemin de la base, utilisateur, mot de passe
	} catch(ClassNotFoundException e) {
            System.err.println("erreur driver non trouvé dans la FenetreMain");
            System.exit(1);
        } catch(SQLException e) {
            System.err.println("erreur SQL au moment de la connection Fenetre Main");
            System.exit(1);
        }
    }
    
    public void ajouter() {
        
        
        String titre = this.titreA.getText();
        String code = this.affichageCodeA.getText();
        String tag1 = this.tagA1.getText();
        String tag2 = this.tagA2.getText();
        String tag3 = this.tagA3.getText();
        String tag4 = this.tagA4.getText();
        
        try {
            requete = connection.prepareStatement("insert into listecode(titre, code, tag1, tag2, tag3, tag4) values (?, ?, ?, ?, ?, ?)");
            requete.setString(1, titre); // 1 => 1er point d'interrogation
            requete.setString(2, code); // 2 => 2ème point d'interrogation
            requete.setString(3, tag1); // 3 => 3ème point d'interrogation
            requete.setString(4, tag2); // 4 => 4ème point d'interrogation
            requete.setString(5, tag3);
            requete.setString(6, tag4);
            requete.executeUpdate();
        } catch(SQLException e) {
            e.printStackTrace();
            System.err.println("erreur lors de l'insertion");
            System.exit(1);	
        }
        
        this.titreA.setText("");
        this.affichageCodeA.setText("");
        this.tagA1.setText("");
        this.tagA2.setText("");
        this.tagA3.setText("");
        this.tagA4.setText("");
        
    }
    
    public void supprimer() {
        Connection connection = null;
	PreparedStatement requete = null;
        
        String titreSelected = ""; /*mlc.getElementAt(index).toString();*/
        
        try {
            requete = connection.prepareStatement("delete from listecode where titre = ?");
            requete.setString(1, titreSelected);
            requete.executeUpdate();
        } catch(SQLException e) {
            e.printStackTrace();
            System.err.println("erreur lors de la suppression");
            System.exit(1);	
        }
    }
    
    public void modifier() {
        Connection connection = null;
	PreparedStatement requete = null;
        
        String titreCode = "";
        String code = "";
        
        try {
		requete = connection.prepareStatement("update listecode set code=? where titre=?");
		requete.setString(1, titreCode);
		requete.setString(2, code);
		requete.executeUpdate();
            } catch(SQLException e) {
		e.printStackTrace();
		System.err.println("erreur lors de la mise à jour");
		System.exit(1);	
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        tagR2 = new javax.swing.JTextField();
        tagR1 = new javax.swing.JTextField();
        tagR4 = new javax.swing.JTextField();
        tagR3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        titreR = new javax.swing.JList();
        affichageCodeR = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titreA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        affichageCodeA = new javax.swing.JTextField();
        tagA1 = new javax.swing.JTextField();
        tagA2 = new javax.swing.JTextField();
        tagA3 = new javax.swing.JTextField();
        tagA4 = new javax.swing.JTextField();
        ajoutDB = new javax.swing.JButton();

        titreR.setModel(mlc);
        titreR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titreRMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(titreR);

        affichageCodeR.setEditable(false);

        jButton1.setText("Supprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(affichageCodeR, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tagR1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(tagR2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(tagR3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(tagR4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addComponent(affichageCodeR, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagR1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagR2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagR4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagR3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jTabbedPane2.addTab("BD", jPanel2);

        jLabel1.setText("Titre");

        jLabel2.setText("Code");

        ajoutDB.setText("Ajouter");
        ajoutDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tagA1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tagA2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(tagA3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(tagA4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(ajoutDB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(affichageCodeA)
                            .addComponent(titreA, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titreA, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(affichageCodeA, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tagA1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagA2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagA3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagA4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajoutDB))
                .addGap(22, 22, 22))
        );

        jTabbedPane2.addTab("Ajouter", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void titreRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titreRMouseClicked
        JList liste = (JList)evt.getSource();
        int index = liste.locationToIndex(evt.getPoint());
        if (evt.getClickCount() == 2) {
            
                String titreCode = mlc.getElementAt(index).toString(); //emplois la methode toString pour retourner le titre
            try {
                requete = connection.prepareStatement("select * from listecode where titre = ?");
                requete.setString(1, titreCode);
                resultat = requete.executeQuery();
                while (resultat.next()) {
                    String code = resultat.getString("code");
                    affichageCodeR.setText(code);
                }
                
            } catch(SQLException e) {
                e.printStackTrace();
                System.err.println("erreur lors de l'insertion");
                System.exit(1);	
            }
        }
    }//GEN-LAST:event_titreRMouseClicked

    private void ajoutDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutDBActionPerformed
        ajouter();
    }//GEN-LAST:event_ajoutDBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        supprimer();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modifier();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField affichageCodeA;
    private javax.swing.JTextField affichageCodeR;
    private javax.swing.JButton ajoutDB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField tagA1;
    private javax.swing.JTextField tagA2;
    private javax.swing.JTextField tagA3;
    private javax.swing.JTextField tagA4;
    private javax.swing.JTextField tagR1;
    private javax.swing.JTextField tagR2;
    private javax.swing.JTextField tagR3;
    private javax.swing.JTextField tagR4;
    private javax.swing.JTextField titreA;
    private javax.swing.JList titreR;
    // End of variables declaration//GEN-END:variables
}
