/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chronometre;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Bamba Mohamed
 */
public class GraphiqueChrono extends javax.swing.JFrame {
    
    Chronometre chrono = new Chronometre();
    
    /**
     * Creates new form GraphiqueChrono
     */
    public GraphiqueChrono() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        boutonDemarrer = new javax.swing.JButton();
        boutonArreter = new javax.swing.JButton();
        boutonMettreZero = new javax.swing.JButton();
        affichage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jLabel2.setText("CHRONOMETRE");
        jToolBar1.add(jLabel2);

        boutonDemarrer.setText("Démarrer");
        boutonDemarrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonDemarrerActionPerformed(evt);
            }
        });

        boutonArreter.setText("Arrêter");
        boutonArreter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonArreterActionPerformed(evt);
            }
        });

        boutonMettreZero.setText("Réinitialiser");

        affichage.setEditable(false);
        affichage.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        affichage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        affichage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affichageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boutonDemarrer)
                    .addComponent(boutonArreter)
                    .addComponent(boutonMettreZero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(affichage, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boutonDemarrer)
                        .addGap(18, 18, 18)
                        .addComponent(boutonArreter)
                        .addGap(18, 18, 18)
                        .addComponent(boutonMettreZero)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(affichage))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonDemarrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonDemarrerActionPerformed
        this.boutonDemarrer.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if(e.getSource() == boutonDemarrer) {
                    Timer timer = new Timer(100, new Affichage(affichage)); // dans action, c'est le JTextField -> champ 
                    timer.start();
                }
            }
        });
    }//GEN-LAST:event_boutonDemarrerActionPerformed

    private void boutonArreterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonArreterActionPerformed
        this.boutonArreter.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if(e.getSource() == boutonArreter) {
                    
                }
            }
        });
    }//GEN-LAST:event_boutonArreterActionPerformed

    private void affichageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affichageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_affichageActionPerformed
    
    private void boutonMettreZeroActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.boutonMettreZero.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if(e.getSource() == boutonMettreZero) {
                    chrono.mettreAZero();
                }
            }
        });
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphiqueChrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphiqueChrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphiqueChrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphiqueChrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphiqueChrono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField affichage;
    private javax.swing.JButton boutonArreter;
    private javax.swing.JButton boutonDemarrer;
    private javax.swing.JButton boutonMettreZero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
